-- 업적 종류 테이블
CREATE TABLE IF NOT EXISTS achievements (
  achievement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  icon VARCHAR(50),
  condition_type VARCHAR(50) NOT NULL, -- 'FIRST_RIDE', 'CONSECUTIVE_DAYS', 'TOTAL_DISTANCE', 'TOTAL_STATIONS', 'TOTAL_RIDES'
  condition_value INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 회원별 달성한 업적
CREATE TABLE IF NOT EXISTS member_achievements (
  member_achievement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT NOT NULL,
  achievement_id INT NOT NULL,
  earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  points_awarded BOOLEAN DEFAULT FALSE,
  CONSTRAINT fk_member_achievement_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_member_achievement_achievement
    FOREIGN KEY (achievement_id) REFERENCES achievements(achievement_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_member_achievement UNIQUE (member_id, achievement_id)
);

-- rentals 테이블에 거리 컬럼 추가
ALTER TABLE rentals ADD COLUMN IF NOT EXISTS distance_km DOUBLE PRECISION;

-- 주별 랭킹 기록 테이블
CREATE TABLE IF NOT EXISTS weekly_rankings (
  ranking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_start_date DATE NOT NULL, -- 주의 시작일 (월요일)
  member_id INT NOT NULL,
  total_distance_km DOUBLE PRECISION NOT NULL DEFAULT 0,
  rank_position INT,
  points_awarded BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_weekly_ranking_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_weekly_member UNIQUE (week_start_date, member_id)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_weekly_rankings_week ON weekly_rankings(week_start_date, total_distance_km DESC);
CREATE INDEX IF NOT EXISTS idx_member_achievements_member ON member_achievements(member_id);
CREATE INDEX IF NOT EXISTS idx_rentals_distance ON rentals(distance_km);

-- 업적 초기 데이터 삽입
INSERT INTO achievements (name, description, icon, condition_type, condition_value) VALUES
('첫 걸음', '첫 따릉이 이용 완료', '🚴', 'FIRST_RIDE', 1),
('초보 라이더', '10회 이용 달성', '🚲', 'TOTAL_RIDES', 10),
('중급 라이더', '50회 이용 달성', '🚴', 'TOTAL_RIDES', 50),
('출퇴근 마스터', '10일 연속 이용', '🏆', 'CONSECUTIVE_DAYS', 10),
('장거리 라이더', '누적 100km 달성', '🎯', 'TOTAL_DISTANCE', 100),
('환경 지킴이', '누적 500km 달성', '🌿', 'TOTAL_DISTANCE', 500),
('전국구', '50개 이상의 대여소 이용', '🗺️', 'TOTAL_STATIONS', 50),
('단골 회원', '100회 이용 달성', '⭐', 'TOTAL_RIDES', 100)
ON CONFLICT DO NOTHING;