-- Station favorites
CREATE TABLE IF NOT EXISTS station_favorites (
  favorite_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     INT NOT NULL,
  station_id    INT NOT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_station_favorites_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_station_favorites_station
    FOREIGN KEY (station_id) REFERENCES stations(station_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_station_favorite UNIQUE (member_id, station_id)
);

CREATE INDEX IF NOT EXISTS idx_station_favorites_member ON station_favorites(member_id);
CREATE INDEX IF NOT EXISTS idx_station_favorites_station ON station_favorites(station_id);
