-- 게시글 첨부파일 테이블 추가
CREATE TABLE IF NOT EXISTS post_attachments (
  attachment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       INT NOT NULL,
  file_name     VARCHAR(255) NOT NULL,     -- 원본 파일명
  file_path     TEXT NOT NULL,             -- 서버 저장 경로
  file_size     BIGINT NOT NULL,           -- 파일 크기 (bytes)
  file_type     VARCHAR(100),              -- MIME 타입
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_attachments_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_post_attachments_post ON post_attachments(post_id);

-- 기존 post_images 테이블에 file_size와 file_name 추가 (선택사항)
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS file_name VARCHAR(255);
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS file_size BIGINT;

