-- 깨끗한 재실행을 위해(옵션)
DROP TABLE IF EXISTS rentals;
DROP TABLE IF EXISTS bikes;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS stations;

-- 대여소
CREATE TABLE stations (
  station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  bike_count INT DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT '정상',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name),
  CHECK (status IN ('정상','점검중','폐쇄'))
);

-- 자전거
CREATE TABLE bikes (
  bike_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id INT,
  status VARCHAR(20) NOT NULL DEFAULT '정상',         -- 정상/고장/수리중
  lock_status VARCHAR(20) NOT NULL DEFAULT 'LOCKED',   -- LOCKED/IN_USE
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CHECK (status IN ('정상','고장','수리중')),
  CHECK (lock_status IN ('LOCKED','IN_USE'))
);

-- 회원
CREATE TABLE members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20),
  has_subscription BOOLEAN DEFAULT FALSE,
  current_latitude DOUBLE PRECISION,
  current_longitude DOUBLE PRECISION,
  last_bike_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (last_bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- 대여 기록
CREATE TABLE rentals (
  rental_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT,
  bike_id INT,
  start_station_id INT,
  end_station_id INT,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (start_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (end_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);


-- 5) REPORT (member:bike = M:N을 신고로 분해)
CREATE TABLE reports (
  report_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id      INT NOT NULL,
  bike_id        INT NOT NULL,
  title          VARCHAR(100) NOT NULL,
  report_content TEXT,
  status         VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending/resolved/rejected
  report_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_report_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_report_bike
    FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (status IN ('pending','resolved','rejected'))
);

-- 6) POST (커뮤니티 게시물)
CREATE TABLE posts (
  post_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id   INT NOT NULL,
  title       VARCHAR(150) NOT NULL,
  content     TEXT,
  category    VARCHAR(30),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- 조회 성능 인덱스(허용 목록: CREATE INDEX)
CREATE INDEX idx_bikes_station ON bikes(station_id);
CREATE INDEX idx_rentals_member_active ON rentals(member_id, end_time);
CREATE INDEX idx_stations_status_bikes ON stations(status, bike_count);

