-- 깨끗한 재실행을 위해(옵션)
DROP TABLE IF EXISTS member_tickets;
DROP TABLE IF EXISTS ticket_types;
DROP TABLE IF EXISTS rentals;
DROP TABLE IF EXISTS bikes;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS stations;

-- 대여소
CREATE TABLE stations (
  station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  bike_count INT DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT '정상',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name),
  CHECK (status IN ('정상','점검중','폐쇄'))
);

-- 자전거
CREATE TABLE bikes (
  bike_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id INT,
  status VARCHAR(20) NOT NULL DEFAULT '정상',         -- 정상/고장/수리중
  lock_status VARCHAR(20) NOT NULL DEFAULT 'LOCKED',   -- LOCKED/IN_USE
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CHECK (status IN ('정상','고장','수리중')),
  CHECK (lock_status IN ('LOCKED','IN_USE'))
);

-- 회원
CREATE TABLE members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20),
  has_subscription BOOLEAN DEFAULT FALSE,
  current_latitude DOUBLE PRECISION,
  current_longitude DOUBLE PRECISION,
  last_bike_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (last_bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- 대여 기록
CREATE TABLE rentals (
  rental_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT,
  bike_id INT,
  start_station_id INT,
  end_station_id INT,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (start_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (end_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);


-- 5) REPORT (member:bike = M:N을 신고로 분해)
CREATE TABLE reports (
  report_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id      INT NOT NULL,
  bike_id        INT NOT NULL,
  title          VARCHAR(100) NOT NULL,
  report_content TEXT,
  status         VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending/resolved/rejected
  report_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_report_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_report_bike
    FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (status IN ('pending','resolved','rejected'))
);

-- 6) POST (커뮤니티 게시물)
CREATE TABLE posts (
  post_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     INT NOT NULL,
  title         VARCHAR(150) NOT NULL,
  content       TEXT,
  category      VARCHAR(30),
  views         INT DEFAULT 0,              -- 조회수
  likes         INT DEFAULT 0,              -- 좋아요 수
  comments_count INT DEFAULT 0,            -- 댓글 수
  is_pinned     BOOLEAN DEFAULT FALSE,       -- 고정 여부 (관리자만 설정 가능)
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7) TICKET_TYPES (이용권 종류)
CREATE TABLE ticket_types (
  ticket_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(50) NOT NULL UNIQUE,  -- '1시간권', '1일권', '정기권', '연간권'
  duration_hours INT NOT NULL,                 -- 유효 기간 (시간 단위)
  price          INT NOT NULL,                 -- 가격 (원)
  description    TEXT,                          -- 설명
  ride_limit_minutes INT,                       -- 1회 이용 제한 시간 (분)
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (duration_hours > 0),
  CHECK (price >= 0)
);

-- 8) MEMBER_TICKETS (회원이 구매한 이용권)
CREATE TABLE member_tickets (
  member_ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id        INT NOT NULL,
  ticket_type_id   INT NOT NULL,
  purchase_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiry_time      TIMESTAMP NOT NULL,          -- 만료 시간
  status           VARCHAR(20) NOT NULL DEFAULT 'active',  -- active/used/expired
  CONSTRAINT fk_member_ticket_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_member_ticket_type
    FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(ticket_type_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (status IN ('active','used','expired'))
);

-- 기본 이용권 종류 데이터 삽입
INSERT INTO ticket_types (name, duration_hours, price, description, ride_limit_minutes) VALUES
('1시간권', 1, 1000, '1시간 동안 이용 가능, 추가 시간당 1,000원', NULL),
('1일권', 24, 2000, '24시간 무제한 이용, 1회 이용시간 2시간까지', 120),
('정기권', 720, 5000, '30일간 무제한 이용, 1회 이용시간 2시간까지', 120),
('연간권', 8760, 30000, '1년간 무제한 이용, 1회 이용시간 2시간까지', 120);

-- 9) COMMENTS (댓글)
CREATE TABLE comments (
  comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    INT NOT NULL,
  member_id  INT NOT NULL,
  content    TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comment_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_comment_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- 10) POST_LIKES (게시글 좋아요)
CREATE TABLE post_likes (
  like_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    INT NOT NULL,
  member_id  INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_like_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_like_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_post_like UNIQUE (post_id, member_id)
);

-- 조회 성능 인덱스(허용 목록: CREATE INDEX)
CREATE INDEX idx_bikes_station ON bikes(station_id);
CREATE INDEX idx_rentals_member_active ON rentals(member_id, end_time);
CREATE INDEX idx_stations_status_bikes ON stations(status, bike_count);
CREATE INDEX idx_member_tickets_member ON member_tickets(member_id);
CREATE INDEX idx_member_tickets_status ON member_tickets(status, expiry_time);
CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_post_likes_post ON post_likes(post_id);
CREATE INDEX idx_post_likes_member ON post_likes(member_id);

