-- 깨끗한 재실행을 위해(옵션)
DROP TABLE IF EXISTS member_tickets CASCADE;
DROP TABLE IF EXISTS point_transactions CASCADE;
DROP TABLE IF EXISTS ticket_types CASCADE;
DROP TABLE IF EXISTS rentals CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS post_attachments CASCADE;
DROP TABLE IF EXISTS post_likes CASCADE;
DROP TABLE IF EXISTS station_favorites CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS post_images CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
-- 추가: 업적 및 랭킹 테이블 (members 의존)
DROP TABLE IF EXISTS weekly_rankings CASCADE;
DROP TABLE IF EXISTS member_achievements CASCADE;
DROP TABLE IF EXISTS achievements CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS bikes CASCADE;
DROP TABLE IF EXISTS stations CASCADE;

-- 대여소
CREATE TABLE stations (
  station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  bike_count INT DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT '정상',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name),
  CHECK (status IN ('정상','점검중','폐쇄'))
);
-- 자전거
CREATE TABLE bikes (
  bike_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id INT,
  status VARCHAR(20) NOT NULL DEFAULT '정상',         -- 정상/고장/수리중
  lock_status VARCHAR(20) NOT NULL DEFAULT 'LOCKED',   -- LOCKED/IN_USE
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CHECK (status IN ('정상','고장','수리중')),
  CHECK (lock_status IN ('LOCKED','IN_USE'))
);

-- 회원
CREATE TABLE members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'user',
  point_balance INT NOT NULL DEFAULT 0,
  has_subscription BOOLEAN DEFAULT FALSE,
  current_latitude DOUBLE PRECISION,
  current_longitude DOUBLE PRECISION,
  last_bike_id INT,
  kakao_id BIGINT UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (last_bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- Station favorites
CREATE TABLE station_favorites (
  favorite_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     INT NOT NULL,
  station_id    INT NOT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_station_favorites_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_station_favorites_station
    FOREIGN KEY (station_id) REFERENCES stations(station_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_station_favorite UNIQUE (member_id, station_id)
);

-- 대여 기록
CREATE TABLE rentals (
  rental_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT,
  bike_id INT,
  start_station_id INT,
  end_station_id INT,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  distance_km DOUBLE PRECISION,
  FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (start_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (end_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- 업적 종류 테이블
CREATE TABLE achievements (
  achievement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  icon VARCHAR(50),
  condition_type VARCHAR(50) NOT NULL, -- 'FIRST_RIDE', 'CONSECUTIVE_DAYS', 'TOTAL_DISTANCE', 'TOTAL_STATIONS', 'TOTAL_RIDES'
  condition_value INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 회원별 달성한 업적
CREATE TABLE member_achievements (
  member_achievement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT NOT NULL,
  achievement_id INT NOT NULL,
  earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  points_awarded BOOLEAN DEFAULT FALSE,
  CONSTRAINT fk_member_achievement_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_member_achievement_achievement
    FOREIGN KEY (achievement_id) REFERENCES achievements(achievement_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_member_achievement UNIQUE (member_id, achievement_id)
);

-- 주별 랭킹 기록 테이블
CREATE TABLE weekly_rankings (
  ranking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_start_date DATE NOT NULL, -- 주의 시작일 (월요일)
  member_id INT NOT NULL,
  total_distance_km DOUBLE PRECISION NOT NULL DEFAULT 0,
  rank_position INT,
  points_awarded BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_weekly_ranking_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_weekly_member UNIQUE (week_start_date, member_id)
);

-- 5) REPORT (member:bike = M:N을 신고로 분해)
CREATE TABLE reports (
  report_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id      INT NOT NULL,
  bike_id        INT NOT NULL,
  title          VARCHAR(100) NOT NULL,
  report_content TEXT,
  status         VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending/resolved/rejected
  report_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_report_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_report_bike
    FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (status IN ('pending','resolved','rejected'))
);

-- 포인트 트랜잭션
CREATE TABLE point_transactions (
  transaction_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id       INT NOT NULL,
  amount          INT NOT NULL,
  type            VARCHAR(20) NOT NULL,
  description     TEXT,
  balance_after   INT NOT NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_point_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (type IN ('CHARGE','USE','ADJUST'))
);

CREATE INDEX idx_point_transactions_member ON point_transactions(member_id, created_at DESC);

-- 6) POST (커뮤니티 게시물)
CREATE TABLE posts (
  post_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id     INT NOT NULL,
  title         VARCHAR(150) NOT NULL,
  content       TEXT,
  category      VARCHAR(30),
  views         INT DEFAULT 0,              -- 조회수
  likes         INT DEFAULT 0,              -- 좋아요 수
  comments_count INT DEFAULT 0,            -- 댓글 수
  is_pinned     BOOLEAN DEFAULT FALSE,       -- 고정 여부 (관리자만 설정 가능)
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- 게시글 이미지
CREATE TABLE post_images (
  image_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    INT NOT NULL,
  image_url  TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_images_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_post_images_post ON post_images(post_id);

-- 7) TICKET_TYPES (이용권 종류)
CREATE TABLE ticket_types (
  ticket_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(50) NOT NULL UNIQUE,  -- '1시간권', '1일권', '정기권', '연간권'
  duration_hours INT NOT NULL,                 -- 유효 기간 (시간 단위)
  price          INT NOT NULL,                 -- 가격 (원)
  description    TEXT,                          -- 설명
  ride_limit_minutes INT,                       -- 1회 이용 제한 시간 (분)
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHECK (duration_hours > 0),
  CHECK (price >= 0)
);

-- 8) MEMBER_TICKETS (회원이 구매한 이용권)
CREATE TABLE member_tickets (
  member_ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id        INT NOT NULL,
  ticket_type_id   INT NOT NULL,
  purchase_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiry_time      TIMESTAMP NOT NULL,          -- 만료 시간
  status           VARCHAR(20) NOT NULL DEFAULT 'active',  -- active/used/expired
  CONSTRAINT fk_member_ticket_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_member_ticket_type
    FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(ticket_type_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (status IN ('active','used','expired'))
);

-- 기본 이용권 종류 데이터 삽입
INSERT INTO ticket_types (name, duration_hours, price, description, ride_limit_minutes) VALUES
('1시간권', 1, 1000, '1시간 동안 이용 가능,추가 시간당 1000원', 60),
('1일권', 24, 2000, '24시간 무제한 이용,1회 이용시간 2시간까지', 120),
('정기권', 720, 5000, '30일간 무제한 이용,1회 이용시간 2시간까지', 120),
('연간권', 8760, 30000, '1년간 무제한 이용,1회 이용시간 2시간까지', 120);

-- 업적 초기 데이터 삽입
INSERT INTO achievements (name, description, icon, condition_type, condition_value) VALUES
('첫 걸음', '첫 따릉이 이용 완료', '🚴', 'FIRST_RIDE', 1),
('초보 라이더', '10회 이용 달성', '🚲', 'TOTAL_RIDES', 10),
('중급 라이더', '50회 이용 달성', '🚴', 'TOTAL_RIDES', 50),
('출퇴근 마스터', '10일 연속 이용', '🏆', 'CONSECUTIVE_DAYS', 10),
('장거리 라이더', '누적 100km 달성', '🎯', 'TOTAL_DISTANCE', 100),
('환경 지킴이', '누적 500km 달성', '🌿', 'TOTAL_DISTANCE', 500),
('전국구', '50개 이상의 대여소 이용', '🗺️', 'TOTAL_STATIONS', 50),
('단골 회원', '100회 이용 달성', '⭐', 'TOTAL_RIDES', 100);

-- 9) COMMENTS (댓글)
CREATE TABLE comments (
  comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    INT NOT NULL,
  member_id  INT NOT NULL,
  content    TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_comment_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_comment_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

-- 10) POST_LIKES (게시글 좋아요)
CREATE TABLE post_likes (
  like_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    INT NOT NULL,
  member_id  INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_like_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_like_member
    FOREIGN KEY (member_id) REFERENCES members(member_id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT unique_post_like UNIQUE (post_id, member_id)
);

-- 조회 성능 인덱스(허용 목록: CREATE INDEX)
CREATE INDEX idx_bikes_station ON bikes(station_id);
CREATE INDEX idx_rentals_member_active ON rentals(member_id, end_time);
CREATE INDEX idx_stations_status_bikes ON stations(status, bike_count);
CREATE INDEX idx_member_tickets_member ON member_tickets(member_id);
CREATE INDEX idx_member_tickets_status ON member_tickets(status, expiry_time);
CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_post_likes_post ON post_likes(post_id);
CREATE INDEX idx_post_likes_member ON post_likes(member_id);
CREATE INDEX idx_station_favorites_member ON station_favorites(member_id);
CREATE INDEX idx_station_favorites_station ON station_favorites(station_id);
CREATE INDEX idx_members_kakao_id ON members(kakao_id);
-- 업적 및 랭킹 인덱스
CREATE INDEX idx_weekly_rankings_week ON weekly_rankings(week_start_date, total_distance_km DESC);
CREATE INDEX idx_member_achievements_member ON member_achievements(member_id);
CREATE INDEX idx_rentals_distance ON rentals(distance_km);


-- 게시글 첨부파일 테이블 추가
CREATE TABLE IF NOT EXISTS post_attachments (
  attachment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       INT NOT NULL,
  file_name     VARCHAR(255) NOT NULL,     -- 원본 파일명
  file_path     TEXT NOT NULL,             -- 서버 저장 경로
  file_size     BIGINT NOT NULL,           -- 파일 크기 (bytes)
  file_type     VARCHAR(100),              -- MIME 타입
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_attachments_post
    FOREIGN KEY (post_id) REFERENCES posts(post_id)
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_post_attachments_post ON post_attachments(post_id);

-- 기존 post_images 테이블에 file_size와 file_name 추가 (선택사항)
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS file_name VARCHAR(255);
ALTER TABLE post_images ADD COLUMN IF NOT EXISTS file_size BIGINT;

-- 테스트용 회원 데이터 (암호는 $2b$10$N9qo8uLOickgx2ZMRZoMye로 "password" hashed)
INSERT INTO members (username, email, password, role, point_balance, has_subscription) VALUES
('admin_user', 'admin@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'admin', 10000, true),
('user_kim', 'kim@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 5000, false),
('user_lee', 'lee@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 3500, true),
('user_park', 'park@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 2000, false),
('user_choi', 'choi@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 4500, true),
('user_jung', 'jung@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 1800, false),
('user_kang', 'kang@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 6000, true),
('user_jo', 'jo@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 3200, false),
('user_oh', 'oh@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 2800, true),
('user_seo', 'seo@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 5200, false),
('user_han', 'han@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 4100, true),
('user_moon', 'moon@example.com', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcg7Eb2fQ7XkuNEH5GhvB8S8Baa', 'user', 3600, false) ON CONFLICT DO NOTHING;
