-- Imported from OneDrive postgrelsql/MakeTable.sql
-- =================================================================
-- 1. 사용자 정의 타입 및 테이블 생성 DDL CHECK 
-- =================================================================

-- 1. 대여소 테이블 (
CREATE TABLE stations (
    station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(10) DEFAULT '정상' CHECK (status IN ('정상', '점검중', '폐쇄')),
    bike_count SMALLINT DEFAULT 0 CHECK (bike_count >= 0),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    operational_details JSONB NULL
);
COMMENT ON TABLE stations IS '대여소 정보 테이블';
COMMENT ON COLUMN stations.bike_count IS '현재 주차된 자전거 수';

-- 2. 자전거 테이블 
CREATE TABLE bikes (
    bike_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id INT,
    status VARCHAR(10) DEFAULT '정상' CHECK (status IN ('정상', '고장', '수리중','대여중')),
    lock_status VARCHAR(10) DEFAULT 'LOCKED' CHECK (lock_status IN ('LOCKED', 'IN_USE','UNLOKED')),
    maintenance_log TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (station_id) REFERENCES stations(station_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);
COMMENT ON TABLE bikes IS '자전거 정보 테이블';

-- 3. 회원 테이블 
CREATE TABLE members (
    member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(10) DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    has_subscription BOOLEAN DEFAULT FALSE,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    last_bike_id BIGINT,
    join_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY (last_bike_id) REFERENCES bikes(bike_id)
        ON UPDATE CASCADE ON DELETE SET NULL
);
COMMENT ON TABLE members IS '회원 정보 테이블';

-- 4. 대여 기록 테이블 
CREATE TABLE rentals (
  rental_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT,
  bike_id INT,
  start_station_id INT,
  end_station_id INT,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  FOREIGN KEY (member_id) REFERENCES members(member_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (bike_id) REFERENCES bikes(bike_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (start_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (end_station_id) REFERENCES stations(station_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);
COMMENT ON TABLE rentals IS '대여/반납 기록 테이블';

-- 1.5 ~ 1.10 FAQ, 문의, 게시판 관련 테이블 생성 (변경 없음)
CREATE TABLE faq_categories ( category_id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, sort_order INT DEFAULT 0, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP );
CREATE TABLE faq_documents ( document_id SERIAL PRIMARY KEY, category_id INT, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, is_pinned BOOLEAN DEFAULT FALSE, view_count INT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES faq_categories(category_id) );
CREATE TABLE faq_feedbacks ( feedback_id SERIAL PRIMARY KEY, document_id INT, member_id INT, is_helpful BOOLEAN NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (document_id) REFERENCES faq_documents(document_id), FOREIGN KEY (member_id) REFERENCES members(member_id) );
CREATE TABLE inquiries ( inquiry_id SERIAL PRIMARY KEY, member_id INT, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, category_id INT, bike_id BIGINT NULL, station_id INT NULL, status VARCHAR(20) DEFAULT '처리중', created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (member_id) REFERENCES members(member_id), FOREIGN KEY (category_id) REFERENCES faq_categories(category_id), FOREIGN KEY (bike_id) REFERENCES bikes(bike_id), FOREIGN KEY (station_id) REFERENCES stations(station_id) );
CREATE TABLE inquiry_images ( image_id SERIAL PRIMARY KEY, inquiry_id INT, image_url VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (inquiry_id) REFERENCES inquiries(inquiry_id) );
CREATE TABLE posts ( post_id SERIAL PRIMARY KEY, member_id INT, title VARCHAR(200), content TEXT, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (member_id) REFERENCES members(member_id) );

